### ISSUE TITLE
frontendchecklist.io links to NSFW content (thedaviddias.me)

### ISSUE THREAD

**Issue by digitalfu** [thedaviddias/Front-End-Checklist#475] opened 2022-02-17 01:17 UTC
Please label with a suitable warning or merge [#474](https://github.com/thedaviddias/Front-End-Checklist/pull/474/files) and buy @BenjaminMichaelis a beer (offline). 

Also, it's worth considering the point below which has since been included in [Contributor Covenant](http://contributor-covenant.org/):
> Accepting responsibility and apologizing to those affected by our mistakes, and learning from the experience

**Comment by DavidMorenoDev** [comment] 2022-04-27 06:40
Yeah is a porn paga :/

**Comment by thedaviddias** [comment] 2022-06-03 19:56
@DavidMorenoDev the issue is now fixed in production! Thanks for the patience!

**Closed** 2022-06-03 20:00 UTC
